import PDFDocument from "pdfkit";
import type {
  BodyZoneStats,
  SensationStats,
  IntensityTrendPoint,
  ClientAnalyticsResult,
} from "@src/somatic-logs/analytics";

export interface SessionData {
  id: string;
  sessionDate: Date;
  sessionNumber?: number | null;
  topic?: string | null;
  sharedSummary?: string | null;
}

export interface ClientData {
  name: string;
  email?: string;
}

/**
 * Generate analytics PDF as base64 string
 */
export async function generateAnalyticsPdf(
  clientData: ClientData,
  analytics: ClientAnalyticsResult,
  sessions: SessionData[],
  period: string,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument();
      const chunks: Buffer[] = [];

      // Collect PDF chunks as buffer
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => {
        resolve(Buffer.concat(chunks));
      });
      doc.on("error", reject);

      // ========== HEADER ==========
      doc
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("Somatic Analytics Report", { align: "center" });
      doc.moveDown(0.3);

      // Client info
      doc.fontSize(12).font("Helvetica");
      doc.text(`Client: ${clientData.name}`, { align: "center" });
      if (clientData.email) {
        doc.text(`Email: ${clientData.email}`, { align: "center" });
      }
      doc.text(`Report Period: ${period}`, { align: "center" });
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, {
        align: "center",
      });

      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown(0.5);

      // ========== ANALYTICS SUMMARY ==========
      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .text("Analytics Summary", { align: "left" });
      doc.moveDown(0.3);

      doc.fontSize(11).font("Helvetica");
      doc.text(`Total Logs in Period: ${analytics.totalLogsInPeriod}`);
      doc.moveDown(0.3);

      // ========== TOP BODY ZONES TABLE ==========
      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .text("Top Body Zones", { align: "left" });
      doc.moveDown(0.2);

      if (analytics.topBodyZones.length > 0) {
        drawTable(
          doc,
          ["Zone", "Count", "Avg Intensity"],
          analytics.topBodyZones.map((zone: BodyZoneStats) => [
            zone.zone,
            zone.count.toString(),
            zone.avgIntensity.toString(),
          ]),
        );
      } else {
        doc.fontSize(10).text("No data available");
      }

      doc.moveDown(0.4);

      // ========== TOP SENSATIONS TABLE ==========
      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .text("Top Sensations", { align: "left" });
      doc.moveDown(0.2);

      if (analytics.topSensations.length > 0) {
        drawTable(
          doc,
          ["Sensation", "Count", "Avg Intensity"],
          analytics.topSensations.map((sensation: SensationStats) => [
            sensation.sensation,
            sensation.count.toString(),
            sensation.avgIntensity.toString(),
          ]),
        );
      } else {
        doc.fontSize(10).text("No data available");
      }

      doc.moveDown(0.4);

      // ========== INTENSITY TREND TABLE ==========
      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .text("Weekly Intensity Trend", { align: "left" });
      doc.moveDown(0.2);

      if (analytics.intensityTrendOverTime.length > 0) {
        drawTable(
          doc,
          ["Week Starting", "Avg Intensity"],
          analytics.intensityTrendOverTime.map((trend: IntensityTrendPoint) => [
            new Date(trend.weekStart).toLocaleDateString(),
            trend.avgIntensity.toString(),
          ]),
        );
      } else {
        doc.fontSize(10).text("No data available");
      }

      doc.moveDown(0.5);

      // ========== SESSION HISTORY ==========
      if (sessions.length > 0) {
        doc
          .fontSize(14)
          .font("Helvetica-Bold")
          .text("Session History", { align: "left" });
        doc.moveDown(0.2);

        drawTable(
          doc,
          ["Session #", "Date", "Topic", "Summary"],
          sessions.map((session) => [
            session.sessionNumber?.toString() || "-",
            new Date(session.sessionDate).toLocaleDateString(),
            session.topic || "-",
            (session.sharedSummary || "-").substring(0, 40), // Truncate for table
          ]),
        );

        doc.moveDown(0.4);
      }

      // ========== FOOTER ==========
      doc.fontSize(9).font("Helvetica");
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown(0.2);
      doc.text("Generated by Loom Platform - Somatic Coaching System", {
        align: "center",
      });
      doc.text(`${new Date().toLocaleString()}`, { align: "center" });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Draw a simple table on PDF document
 * @param doc PDFKit document
 * @param headers Column headers
 * @param rows Table rows (array of cell values)
 */
function drawTable(
  doc: PDFKit.PDFDocument,
  headers: string[],
  rows: string[][],
): void {
  const startX = 50;
  const startY = doc.y;
  const cellHeight = 25;
  const columnWidth = 500 / headers.length;

  // Draw header row
  doc.font("Helvetica-Bold").fontSize(10);

  let x = startX;
  for (const header of headers) {
    doc.rect(x, startY, columnWidth, cellHeight).stroke();
    doc.text(header, x + 5, startY + 5, {
      width: columnWidth - 10,
      height: cellHeight - 10,
      align: "left",
    });
    x += columnWidth;
  }

  // Draw data rows
  doc.font("Helvetica").fontSize(9);
  let y = startY + cellHeight;

  for (const row of rows) {
    let x = startX;
    for (let i = 0; i < headers.length; i++) {
      doc.rect(x, y, columnWidth, cellHeight).stroke();
      const cellText: string = row[i] || "";
      doc.text(cellText, x + 5, y + 5, {
        width: columnWidth - 10,
        height: cellHeight - 10,
        align: "left",
      });
      x += columnWidth;
    }
    y += cellHeight;
  }

  // Move cursor past table
  doc.y = y;
}

/**
 * Convert buffer to base64 string for transmission
 */
export function bufferToBase64(buffer: Buffer): string {
  return buffer.toString("base64");
}

/**
 * Convert base64 string back to buffer
 */
export function base64ToBuffer(base64: string): Buffer {
  return Buffer.from(base64, "base64");
}

/**
 * Generate filename for PDF export
 */
export function generatePdfFilename(
  clientName: string,
  period: string,
): string {
  const sanitizedName = clientName.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  const timestamp = new Date().toISOString().split("T")[0];
  return `somatic-report-${sanitizedName}-${period}-${timestamp}.pdf`;
}
